/**
 * Redis Commands
 * Comprehensive Redis commands organized by category for query builder and autocomplete
 */

export interface RedisCommand {
  cmd: string;
  args: string;
  desc: string;
  example: string;
}

export const REDIS_COMMANDS: Record<string, RedisCommand[]> = {
  strings: [
    { cmd: "GET", args: "key", desc: "Get the value of a key", example: 'GET user:1001:name' },
    { cmd: "SET", args: "key value [EX seconds] [NX|XX]", desc: "Set string value", example: 'SET user:1001:name "John Doe"' },
    { cmd: "SETEX", args: "key seconds value", desc: "Set with expiration", example: 'SETEX session:abc123 3600 "user_data"' },
    { cmd: "SETNX", args: "key value", desc: "Set if not exists", example: 'SETNX lock:resource1 "locked"' },
    { cmd: "MGET", args: "key [key ...]", desc: "Get multiple keys", example: 'MGET user:1:name user:2:name user:3:name' },
    { cmd: "MSET", args: "key value [key value ...]", desc: "Set multiple keys", example: 'MSET user:1:name "John" user:1:email "john@example.com"' },
    { cmd: "INCR", args: "key", desc: "Increment by 1", example: 'INCR page:views:homepage' },
    { cmd: "INCRBY", args: "key increment", desc: "Increment by value", example: 'INCRBY user:1001:points 100' },
    { cmd: "INCRBYFLOAT", args: "key increment", desc: "Increment by float", example: 'INCRBYFLOAT product:price 19.99' },
    { cmd: "DECR", args: "key", desc: "Decrement by 1", example: 'DECR inventory:item:1001' },
    { cmd: "DECRBY", args: "key decrement", desc: "Decrement by value", example: 'DECRBY inventory:item:1001 5' },
    { cmd: "APPEND", args: "key value", desc: "Append to string", example: 'APPEND log:today " - New entry"' },
    { cmd: "STRLEN", args: "key", desc: "Get string length", example: 'STRLEN article:1001:content' },
    { cmd: "GETRANGE", args: "key start end", desc: "Get substring", example: 'GETRANGE message:1 0 99' },
    { cmd: "SETRANGE", args: "key offset value", desc: "Overwrite part of string", example: 'SETRANGE greeting 6 "Redis"' },
    { cmd: "GETSET", args: "key value", desc: "Set and return old value", example: 'GETSET counter "0"' },
    { cmd: "GETEX", args: "key [EX|PX|EXAT|PXAT|PERSIST]", desc: "Get and set expiry", example: 'GETEX mykey EX 60' },
    { cmd: "GETDEL", args: "key", desc: "Get and delete", example: 'GETDEL temp:data' },
  ],
  hashes: [
    { cmd: "HSET", args: "key field value [field value ...]", desc: "Set hash fields", example: 'HSET user:1001 name "John" email "john@example.com" age "30"' },
    { cmd: "HGET", args: "key field", desc: "Get hash field", example: 'HGET user:1001 email' },
    { cmd: "HGETALL", args: "key", desc: "Get all fields and values", example: 'HGETALL user:1001' },
    { cmd: "HMSET", args: "key field value [field value ...]", desc: "Set multiple fields", example: 'HMSET product:1001 name "Laptop" price "999" stock "50"' },
    { cmd: "HMGET", args: "key field [field ...]", desc: "Get multiple fields", example: 'HMGET user:1001 name email age' },
    { cmd: "HDEL", args: "key field [field ...]", desc: "Delete fields", example: 'HDEL user:1001 temp_field old_field' },
    { cmd: "HEXISTS", args: "key field", desc: "Check if field exists", example: 'HEXISTS user:1001 email' },
    { cmd: "HKEYS", args: "key", desc: "Get all field names", example: 'HKEYS user:1001' },
    { cmd: "HVALS", args: "key", desc: "Get all values", example: 'HVALS user:1001' },
    { cmd: "HLEN", args: "key", desc: "Get number of fields", example: 'HLEN user:1001' },
    { cmd: "HINCRBY", args: "key field increment", desc: "Increment field by int", example: 'HINCRBY user:1001 login_count 1' },
    { cmd: "HINCRBYFLOAT", args: "key field increment", desc: "Increment field by float", example: 'HINCRBYFLOAT product:1001 price 5.50' },
    { cmd: "HSETNX", args: "key field value", desc: "Set field if not exists", example: 'HSETNX user:1001 created_at "2024-01-01"' },
    { cmd: "HSTRLEN", args: "key field", desc: "Get field value length", example: 'HSTRLEN user:1001 bio' },
    { cmd: "HSCAN", args: "key cursor [MATCH pattern] [COUNT count]", desc: "Iterate hash fields", example: 'HSCAN user:1001 0 MATCH "*name*" COUNT 10' },
  ],
  lists: [
    { cmd: "LPUSH", args: "key element [element ...]", desc: "Prepend elements", example: 'LPUSH notifications:user:1001 "New message"' },
    { cmd: "RPUSH", args: "key element [element ...]", desc: "Append elements", example: 'RPUSH queue:tasks "task1" "task2" "task3"' },
    { cmd: "LPOP", args: "key [count]", desc: "Remove and get from head", example: 'LPOP queue:tasks' },
    { cmd: "RPOP", args: "key [count]", desc: "Remove and get from tail", example: 'RPOP queue:tasks 2' },
    { cmd: "LRANGE", args: "key start stop", desc: "Get range of elements", example: 'LRANGE recent:posts 0 9' },
    { cmd: "LINDEX", args: "key index", desc: "Get element by index", example: 'LINDEX mylist 0' },
    { cmd: "LSET", args: "key index element", desc: "Set element by index", example: 'LSET mylist 0 "updated_value"' },
    { cmd: "LLEN", args: "key", desc: "Get list length", example: 'LLEN queue:tasks' },
    { cmd: "LINSERT", args: "key BEFORE|AFTER pivot element", desc: "Insert element", example: 'LINSERT mylist BEFORE "pivot" "new_element"' },
    { cmd: "LREM", args: "key count element", desc: "Remove elements", example: 'LREM mylist 2 "duplicate"' },
    { cmd: "LTRIM", args: "key start stop", desc: "Trim list to range", example: 'LTRIM recent:activity 0 99' },
    { cmd: "LPOS", args: "key element [RANK rank] [COUNT count]", desc: "Get element position", example: 'LPOS mylist "target" COUNT 2' },
    { cmd: "LMOVE", args: "source destination LEFT|RIGHT LEFT|RIGHT", desc: "Move element between lists", example: 'LMOVE source dest LEFT RIGHT' },
    { cmd: "BLPOP", args: "key [key ...] timeout", desc: "Blocking pop from head", example: 'BLPOP queue:tasks 30' },
    { cmd: "BRPOP", args: "key [key ...] timeout", desc: "Blocking pop from tail", example: 'BRPOP queue:tasks 30' },
  ],
  sets: [
    { cmd: "SADD", args: "key member [member ...]", desc: "Add members", example: 'SADD tags:article:1001 "redis" "database" "nosql"' },
    { cmd: "SREM", args: "key member [member ...]", desc: "Remove members", example: 'SREM tags:article:1001 "old_tag"' },
    { cmd: "SMEMBERS", args: "key", desc: "Get all members", example: 'SMEMBERS tags:article:1001' },
    { cmd: "SISMEMBER", args: "key member", desc: "Check if member exists", example: 'SISMEMBER users:online "user:1001"' },
    { cmd: "SMISMEMBER", args: "key member [member ...]", desc: "Check multiple members", example: 'SMISMEMBER users:online "user:1001" "user:1002"' },
    { cmd: "SCARD", args: "key", desc: "Get set size", example: 'SCARD users:online' },
    { cmd: "SINTER", args: "key [key ...]", desc: "Intersection of sets", example: 'SINTER user:1:friends user:2:friends' },
    { cmd: "SINTERSTORE", args: "destination key [key ...]", desc: "Store intersection", example: 'SINTERSTORE mutual:friends user:1:friends user:2:friends' },
    { cmd: "SUNION", args: "key [key ...]", desc: "Union of sets", example: 'SUNION tags:post:1 tags:post:2 tags:post:3' },
    { cmd: "SUNIONSTORE", args: "destination key [key ...]", desc: "Store union", example: 'SUNIONSTORE all:tags tags:post:1 tags:post:2' },
    { cmd: "SDIFF", args: "key [key ...]", desc: "Difference of sets", example: 'SDIFF user:1:friends user:2:friends' },
    { cmd: "SDIFFSTORE", args: "destination key [key ...]", desc: "Store difference", example: 'SDIFFSTORE unique:friends user:1:friends user:2:friends' },
    { cmd: "SPOP", args: "key [count]", desc: "Remove random members", example: 'SPOP lottery:entries 3' },
    { cmd: "SRANDMEMBER", args: "key [count]", desc: "Get random members", example: 'SRANDMEMBER featured:products 5' },
    { cmd: "SMOVE", args: "source destination member", desc: "Move member between sets", example: 'SMOVE pending completed "task:1001"' },
    { cmd: "SSCAN", args: "key cursor [MATCH pattern] [COUNT count]", desc: "Iterate set members", example: 'SSCAN users:online 0 MATCH "user:*" COUNT 100' },
  ],
  sortedSets: [
    { cmd: "ZADD", args: "key score member [score member ...]", desc: "Add members with scores", example: 'ZADD leaderboard 1000 "player:1001" 950 "player:1002"' },
    { cmd: "ZREM", args: "key member [member ...]", desc: "Remove members", example: 'ZREM leaderboard "player:inactive"' },
    { cmd: "ZSCORE", args: "key member", desc: "Get member score", example: 'ZSCORE leaderboard "player:1001"' },
    { cmd: "ZRANK", args: "key member", desc: "Get member rank (low to high)", example: 'ZRANK leaderboard "player:1001"' },
    { cmd: "ZREVRANK", args: "key member", desc: "Get member rank (high to low)", example: 'ZREVRANK leaderboard "player:1001"' },
    { cmd: "ZRANGE", args: "key start stop [WITHSCORES]", desc: "Get range by rank", example: 'ZRANGE leaderboard 0 9 WITHSCORES' },
    { cmd: "ZREVRANGE", args: "key start stop [WITHSCORES]", desc: "Get range (high to low)", example: 'ZREVRANGE leaderboard 0 9 WITHSCORES' },
    { cmd: "ZRANGEBYSCORE", args: "key min max [WITHSCORES] [LIMIT]", desc: "Get range by score", example: 'ZRANGEBYSCORE scores 100 200 WITHSCORES LIMIT 0 10' },
    { cmd: "ZREVRANGEBYSCORE", args: "key max min [WITHSCORES]", desc: "Get range by score (reversed)", example: 'ZREVRANGEBYSCORE scores 200 100 WITHSCORES' },
    { cmd: "ZCARD", args: "key", desc: "Get set size", example: 'ZCARD leaderboard' },
    { cmd: "ZCOUNT", args: "key min max", desc: "Count members by score range", example: 'ZCOUNT leaderboard 100 500' },
    { cmd: "ZINCRBY", args: "key increment member", desc: "Increment member score", example: 'ZINCRBY leaderboard 10 "player:1001"' },
    { cmd: "ZLEXCOUNT", args: "key min max", desc: "Count by lex range", example: 'ZLEXCOUNT myset [a [z' },
    { cmd: "ZRANGEBYLEX", args: "key min max [LIMIT offset count]", desc: "Get by lex range", example: 'ZRANGEBYLEX myset [a [z LIMIT 0 10' },
    { cmd: "ZPOPMIN", args: "key [count]", desc: "Remove lowest scoring members", example: 'ZPOPMIN waiting:queue 1' },
    { cmd: "ZPOPMAX", args: "key [count]", desc: "Remove highest scoring members", example: 'ZPOPMAX leaderboard 3' },
    { cmd: "ZINTERSTORE", args: "dest numkeys key [key ...]", desc: "Store intersection", example: 'ZINTERSTORE out 2 zset1 zset2 WEIGHTS 2 3' },
    { cmd: "ZUNIONSTORE", args: "dest numkeys key [key ...]", desc: "Store union", example: 'ZUNIONSTORE out 2 zset1 zset2' },
    { cmd: "ZSCAN", args: "key cursor [MATCH pattern] [COUNT count]", desc: "Iterate sorted set", example: 'ZSCAN leaderboard 0 MATCH "player:*" COUNT 100' },
  ],
  keys: [
    { cmd: "KEYS", args: "pattern", desc: "Find keys by pattern (use SCAN in prod)", example: 'KEYS user:*' },
    { cmd: "SCAN", args: "cursor [MATCH pattern] [COUNT count] [TYPE type]", desc: "Iterate keys safely", example: 'SCAN 0 MATCH user:* COUNT 100 TYPE hash' },
    { cmd: "EXISTS", args: "key [key ...]", desc: "Check if keys exist", example: 'EXISTS user:1001 user:1002 user:1003' },
    { cmd: "DEL", args: "key [key ...]", desc: "Delete keys", example: 'DEL temp:key1 temp:key2' },
    { cmd: "UNLINK", args: "key [key ...]", desc: "Delete keys async", example: 'UNLINK large:key1 large:key2' },
    { cmd: "TYPE", args: "key", desc: "Get key type", example: 'TYPE user:1001' },
    { cmd: "TTL", args: "key", desc: "Get time to live (seconds)", example: 'TTL session:abc123' },
    { cmd: "PTTL", args: "key", desc: "Get time to live (milliseconds)", example: 'PTTL session:abc123' },
    { cmd: "EXPIRE", args: "key seconds", desc: "Set expiration in seconds", example: 'EXPIRE cache:data 3600' },
    { cmd: "PEXPIRE", args: "key milliseconds", desc: "Set expiration in ms", example: 'PEXPIRE temp:data 60000' },
    { cmd: "EXPIREAT", args: "key timestamp", desc: "Set expiration at timestamp", example: 'EXPIREAT mykey 1735689600' },
    { cmd: "PERSIST", args: "key", desc: "Remove expiration", example: 'PERSIST user:1001' },
    { cmd: "RENAME", args: "key newkey", desc: "Rename key", example: 'RENAME old:key new:key' },
    { cmd: "RENAMENX", args: "key newkey", desc: "Rename if new key doesn't exist", example: 'RENAMENX temp:key final:key' },
    { cmd: "COPY", args: "source destination [REPLACE]", desc: "Copy key value", example: 'COPY user:1001 user:1001:backup REPLACE' },
    { cmd: "DUMP", args: "key", desc: "Serialize key", example: 'DUMP mykey' },
    { cmd: "RESTORE", args: "key ttl serialized-value", desc: "Deserialize key", example: 'RESTORE mykey 0 "\\x00\\x03foo..."' },
    { cmd: "OBJECT ENCODING", args: "key", desc: "Get internal encoding", example: 'OBJECT ENCODING mykey' },
    { cmd: "OBJECT FREQ", args: "key", desc: "Get access frequency", example: 'OBJECT FREQ mykey' },
    { cmd: "OBJECT IDLETIME", args: "key", desc: "Get idle time", example: 'OBJECT IDLETIME mykey' },
    { cmd: "TOUCH", args: "key [key ...]", desc: "Update last access time", example: 'TOUCH key1 key2 key3' },
    { cmd: "RANDOMKEY", args: "", desc: "Get random key", example: 'RANDOMKEY' },
  ],
  streams: [
    { cmd: "XADD", args: "key ID field value [field value ...]", desc: "Add entry to stream", example: 'XADD events:user * action "login" user_id "1001" timestamp "2024-01-01"' },
    { cmd: "XREAD", args: "[COUNT count] [BLOCK ms] STREAMS key [key ...] ID [ID ...]", desc: "Read from streams", example: 'XREAD COUNT 10 STREAMS events:user 0' },
    { cmd: "XRANGE", args: "key start end [COUNT count]", desc: "Get range of entries", example: 'XRANGE events:user - + COUNT 100' },
    { cmd: "XREVRANGE", args: "key end start [COUNT count]", desc: "Get range (reversed)", example: 'XREVRANGE events:user + - COUNT 10' },
    { cmd: "XLEN", args: "key", desc: "Get stream length", example: 'XLEN events:user' },
    { cmd: "XINFO STREAM", args: "key [FULL [COUNT count]]", desc: "Get stream info", example: 'XINFO STREAM events:user' },
    { cmd: "XINFO GROUPS", args: "key", desc: "Get consumer groups", example: 'XINFO GROUPS events:user' },
    { cmd: "XINFO CONSUMERS", args: "key groupname", desc: "Get consumers in group", example: 'XINFO CONSUMERS events:user mygroup' },
    { cmd: "XGROUP CREATE", args: "key groupname ID [MKSTREAM]", desc: "Create consumer group", example: 'XGROUP CREATE events:user processors $ MKSTREAM' },
    { cmd: "XGROUP DESTROY", args: "key groupname", desc: "Delete consumer group", example: 'XGROUP DESTROY events:user processors' },
    { cmd: "XREADGROUP", args: "GROUP group consumer STREAMS key ID", desc: "Read as consumer", example: 'XREADGROUP GROUP processors worker1 COUNT 10 STREAMS events:user >' },
    { cmd: "XACK", args: "key group ID [ID ...]", desc: "Acknowledge messages", example: 'XACK events:user processors 1526569495631-0' },
    { cmd: "XPENDING", args: "key group [IDLE min-idle] [start end count] [consumer]", desc: "Get pending entries", example: 'XPENDING events:user processors - + 10' },
    { cmd: "XCLAIM", args: "key group consumer min-idle-time ID [ID ...]", desc: "Claim pending messages", example: 'XCLAIM events:user processors worker2 3600000 1526569495631-0' },
    { cmd: "XDEL", args: "key ID [ID ...]", desc: "Delete entries", example: 'XDEL events:user 1526569495631-0' },
    { cmd: "XTRIM", args: "key MAXLEN|MINID [~] threshold", desc: "Trim stream", example: 'XTRIM events:user MAXLEN ~ 1000' },
  ],
  pubsub: [
    { cmd: "PUBLISH", args: "channel message", desc: "Publish message to channel", example: 'PUBLISH notifications "New order received"' },
    { cmd: "SUBSCRIBE", args: "channel [channel ...]", desc: "Subscribe to channels", example: 'SUBSCRIBE notifications alerts' },
    { cmd: "PSUBSCRIBE", args: "pattern [pattern ...]", desc: "Subscribe to patterns", example: 'PSUBSCRIBE events:* alerts:*' },
    { cmd: "UNSUBSCRIBE", args: "[channel ...]", desc: "Unsubscribe from channels", example: 'UNSUBSCRIBE notifications' },
    { cmd: "PUNSUBSCRIBE", args: "[pattern ...]", desc: "Unsubscribe from patterns", example: 'PUNSUBSCRIBE events:*' },
    { cmd: "PUBSUB CHANNELS", args: "[pattern]", desc: "List active channels", example: 'PUBSUB CHANNELS notifications:*' },
    { cmd: "PUBSUB NUMSUB", args: "[channel ...]", desc: "Count subscribers", example: 'PUBSUB NUMSUB notifications alerts' },
    { cmd: "PUBSUB NUMPAT", args: "", desc: "Count pattern subscriptions", example: 'PUBSUB NUMPAT' },
  ],
  transactions: [
    { cmd: "MULTI", args: "", desc: "Start transaction", example: 'MULTI' },
    { cmd: "EXEC", args: "", desc: "Execute transaction", example: 'EXEC' },
    { cmd: "DISCARD", args: "", desc: "Discard transaction", example: 'DISCARD' },
    { cmd: "WATCH", args: "key [key ...]", desc: "Watch keys for changes", example: 'WATCH user:1001:balance' },
    { cmd: "UNWATCH", args: "", desc: "Unwatch all keys", example: 'UNWATCH' },
  ],
  scripting: [
    { cmd: "EVAL", args: "script numkeys [key ...] [arg ...]", desc: "Execute Lua script", example: 'EVAL "return redis.call(\'GET\', KEYS[1])" 1 mykey' },
    { cmd: "EVALSHA", args: "sha1 numkeys [key ...] [arg ...]", desc: "Execute cached script", example: 'EVALSHA d41d8cd98f00b204e9800998ecf8427e 1 mykey' },
    { cmd: "SCRIPT LOAD", args: "script", desc: "Load script to cache", example: "SCRIPT LOAD \"return redis.call('GET', KEYS[1])\"" },
    { cmd: "SCRIPT EXISTS", args: "sha1 [sha1 ...]", desc: "Check if scripts exist", example: 'SCRIPT EXISTS d41d8cd98f00b204e9800998ecf8427e' },
    { cmd: "SCRIPT FLUSH", args: "[ASYNC|SYNC]", desc: "Clear script cache", example: 'SCRIPT FLUSH' },
    { cmd: "SCRIPT KILL", args: "", desc: "Kill running script", example: 'SCRIPT KILL' },
  ],
  server: [
    { cmd: "PING", args: "[message]", desc: "Test connection", example: 'PING' },
    { cmd: "ECHO", args: "message", desc: "Echo message", example: 'ECHO "Hello Redis"' },
    { cmd: "INFO", args: "[section]", desc: "Get server info", example: 'INFO memory' },
    { cmd: "DBSIZE", args: "", desc: "Get number of keys", example: 'DBSIZE' },
    { cmd: "SELECT", args: "index", desc: "Switch database (0-15)", example: 'SELECT 1' },
    { cmd: "FLUSHDB", args: "[ASYNC|SYNC]", desc: "Clear current database", example: 'FLUSHDB ASYNC' },
    { cmd: "FLUSHALL", args: "[ASYNC|SYNC]", desc: "Clear all databases", example: 'FLUSHALL ASYNC' },
    { cmd: "CONFIG GET", args: "parameter", desc: "Get config value", example: 'CONFIG GET maxmemory' },
    { cmd: "CONFIG SET", args: "parameter value", desc: "Set config value", example: 'CONFIG SET maxmemory 256mb' },
    { cmd: "CLIENT LIST", args: "", desc: "List connected clients", example: 'CLIENT LIST' },
    { cmd: "CLIENT GETNAME", args: "", desc: "Get client name", example: 'CLIENT GETNAME' },
    { cmd: "CLIENT SETNAME", args: "name", desc: "Set client name", example: 'CLIENT SETNAME myapp' },
    { cmd: "CLIENT ID", args: "", desc: "Get client ID", example: 'CLIENT ID' },
    { cmd: "CLIENT KILL", args: "ip:port | ID client-id", desc: "Kill client connection", example: 'CLIENT KILL ID 12345' },
    { cmd: "MEMORY USAGE", args: "key [SAMPLES count]", desc: "Get key memory usage", example: 'MEMORY USAGE user:1001' },
    { cmd: "MEMORY DOCTOR", args: "", desc: "Memory health report", example: 'MEMORY DOCTOR' },
    { cmd: "MEMORY STATS", args: "", desc: "Memory statistics", example: 'MEMORY STATS' },
    { cmd: "TIME", args: "", desc: "Get server time", example: 'TIME' },
    { cmd: "LASTSAVE", args: "", desc: "Last save timestamp", example: 'LASTSAVE' },
    { cmd: "BGSAVE", args: "", desc: "Background save", example: 'BGSAVE' },
    { cmd: "BGREWRITEAOF", args: "", desc: "Background AOF rewrite", example: 'BGREWRITEAOF' },
    { cmd: "DEBUG SLEEP", args: "seconds", desc: "Sleep (for testing)", example: 'DEBUG SLEEP 1' },
    { cmd: "SLOWLOG GET", args: "[count]", desc: "Get slow queries", example: 'SLOWLOG GET 10' },
    { cmd: "SLOWLOG LEN", args: "", desc: "Slow log length", example: 'SLOWLOG LEN' },
    { cmd: "SLOWLOG RESET", args: "", desc: "Clear slow log", example: 'SLOWLOG RESET' },
  ],
  geo: [
    { cmd: "GEOADD", args: "key longitude latitude member [...]", desc: "Add geospatial items", example: 'GEOADD stores -122.4194 37.7749 "store:sf" -73.9857 40.7484 "store:nyc"' },
    { cmd: "GEOPOS", args: "key member [member ...]", desc: "Get positions", example: 'GEOPOS stores "store:sf" "store:nyc"' },
    { cmd: "GEODIST", args: "key member1 member2 [unit]", desc: "Get distance between members", example: 'GEODIST stores "store:sf" "store:nyc" km' },
    { cmd: "GEORADIUS", args: "key lon lat radius m|km|ft|mi [opts]", desc: "Query by radius", example: 'GEORADIUS stores -122.4194 37.7749 100 km WITHDIST COUNT 10' },
    { cmd: "GEORADIUSBYMEMBER", args: "key member radius unit [opts]", desc: "Query radius from member", example: 'GEORADIUSBYMEMBER stores "store:sf" 500 km WITHDIST' },
    { cmd: "GEOSEARCH", args: "key FROMMEMBER|FROMLONLAT BYRADIUS|BYBOX", desc: "Search geospatial", example: 'GEOSEARCH stores FROMMEMBER "store:sf" BYRADIUS 100 km ASC COUNT 5' },
    { cmd: "GEOHASH", args: "key member [member ...]", desc: "Get geohash strings", example: 'GEOHASH stores "store:sf"' },
  ],
  hyperloglog: [
    { cmd: "PFADD", args: "key element [element ...]", desc: "Add to HyperLogLog", example: 'PFADD visitors:today "user:1001" "user:1002" "user:1003"' },
    { cmd: "PFCOUNT", args: "key [key ...]", desc: "Get cardinality estimate", example: 'PFCOUNT visitors:today visitors:yesterday' },
    { cmd: "PFMERGE", args: "destkey sourcekey [sourcekey ...]", desc: "Merge HyperLogLogs", example: 'PFMERGE visitors:week visitors:mon visitors:tue visitors:wed' },
  ],
  bitmap: [
    { cmd: "SETBIT", args: "key offset value", desc: "Set bit at offset", example: 'SETBIT user:1001:logins 0 1' },
    { cmd: "GETBIT", args: "key offset", desc: "Get bit at offset", example: 'GETBIT user:1001:logins 0' },
    { cmd: "BITCOUNT", args: "key [start end]", desc: "Count set bits", example: 'BITCOUNT user:1001:logins' },
    { cmd: "BITOP", args: "operation destkey key [key ...]", desc: "Bitwise operation", example: 'BITOP AND result key1 key2' },
    { cmd: "BITPOS", args: "key bit [start [end]]", desc: "Find first bit", example: 'BITPOS user:logins 1' },
    { cmd: "BITFIELD", args: "key [GET type offset] [SET type offset value]", desc: "Bit field operations", example: 'BITFIELD mykey GET u8 0 SET u8 8 200' },
  ],
};

// Flatten all commands for autocomplete
export const ALL_REDIS_COMMANDS = Object.values(REDIS_COMMANDS).flat();

// Get command category labels for reference panel
export const REDIS_COMMAND_CATEGORIES = [
  { key: 'strings', label: 'Strings' },
  { key: 'hashes', label: 'Hashes' },
  { key: 'lists', label: 'Lists' },
  { key: 'sets', label: 'Sets' },
  { key: 'sortedSets', label: 'Sorted Sets' },
  { key: 'keys', label: 'Keys' },
  { key: 'streams', label: 'Streams' },
  { key: 'pubsub', label: 'Pub/Sub' },
  { key: 'transactions', label: 'Transactions' },
  { key: 'scripting', label: 'Scripting' },
  { key: 'server', label: 'Server' },
  { key: 'geo', label: 'Geo' },
  { key: 'hyperloglog', label: 'HyperLogLog' },
  { key: 'bitmap', label: 'Bitmap' },
] as const;
